version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - hf_cache:/root/.cache/huggingface
    env_file:
      - .env

  evals:
    build:
      context: .
      dockerfile: Dockerfile.evals
    ports:
      - "8501:8501"
    volumes:
      - hf_cache:/root/.cache/huggingface
    env_file:
      - .env

volumes:
  hf_cache:
